# running with REST Client (https://marketplace.visualstudio.com/items?itemName=humao.rest-client) on Vscode
# TODO:
# 1. input api key (remove "<" and ">")
# 2. change "dc_OLuJQdB" to your source id

curl -X GET \
  -H "Authorization: Bearer <api key>" \
  "https://api.pipedream.com/v1/sources/dc_OLuJQdB/event_summaries?expand=event"